name: Release Go Binaries  
  
on:  
  push:  
    tags:  
      - 'v*.*.*'  # 匹配所有以 v 开头的 tag  
  
jobs:  
  build-and-release:  
    runs-on: ubuntu-latest  

    permissions:
      contents: write

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  
  
      - name: Set up Go  
        uses: actions/setup-go@v5  
        with:  
          go-version: 1.22
  
      - name: Build binaries  
        env:  
          CGO_ENABLED: 0  # 禁用 CGO 以创建静态链接的二进制文件  
        run: |
          platforms="linux/amd64 linux/arm64 windows/amd64 windows/arm64 darwin/amd64 darwin/arm64"
          for platform in $platforms; do
            os=$(echo $platform | cut -d'/' -f1)
            arch=$(echo $platform | cut -d'/' -f2)
            echo "Building $os-$arch"
            GOOS=$os GOARCH=$arch go build -o kubetea-$os-$arch ./
          done

      - name: Upload Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            kubetea-linux-amd64
            kubetea-linux-arm64
            kubetea-windows-amd64
            kubetea-windows-arm64
            kubetea-darwin-amd64
            kubetea-darwin-arm64

